name: Go

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: |
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
          GOARCH=amd64
          output=bin/dchook-${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
          [ "${{ matrix.os }}" = "windows-latest" ] && output="${output}.exe"
          env GOOS=$GOOS GOARCH=$GOARCH go build -v -o $output ./...

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
